plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bbbgolf.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'com.bbbgolf.mobile'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '0.2.2'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
