plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pickemwarroom.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'com.pickemwarroom.mobile'
        minSdk 26
        targetSdk 36
        versionCode 6
        versionName '0.4.5-mobile6'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
